# limaflix:controllers
from .usuario_controller import UsuarioController
from .filme_controller import FilmeController
from .temporada_controller import TemporadaController
from .episodeo_controller import EpisodeoController
from .vitrine_controller import VitrineController
from .comentario_controller import ComentarioController